services:
  - type: web
    name: atlas-earth-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_AUDIENCE_ID
        sync: false
